name: Document Publish

on:
  push:
    paths:
      - 'doc/**'
    tags:
      - 'v*'       
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
 
      - name: Generate PDF
        uses: BaileyJM02/markdown-to-pdf@v1.0.1
        with:
          input_dir: doc
          output_dir: dist
          build_html: false
          
      - name: Setup GitVersion
        run: |
          git fetch --unshallow 
          dotnet tool install -g GitVersion.Tool --version=5.6.0 
          dotnet gitversion /output json /config "${{ github.workspace }}/GitVersion.yml"
          echo "SemVer=$(dotnet gitversion /output json /config "${{ github.workspace }}/GitVersion.yml" /showvariable SemVer /verbosity Quiet)" >> $GITHUB_ENV

      - name: 📋 Get Commits since last Release
        id: changes
        uses: simbo/changes-since-last-release-action@v1           
      
      - name: Pre-release check
        env:
          IS_TAG: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          if [[ $IS_TAG -eq "true" ]] 
          then
              echo "PreRelease=false" >> $GITHUB_ENV
          else
              echo "PreRelease=true" >> $GITHUB_ENV
          fi
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.SemVer }}
          release_name: Release ${{ env.SemVer }}
          body: ${{ steps.changes.outputs.log }}
          draft: false
          prerelease: ${{ env.PreRelease }}
                            
      - name: Upload PDF as Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./dist/rpg.pdf
          asset_name: yu-yu-hakusho-rpg.${{ env.SemVer }}.pdf
          asset_content_type: application/pdf
